typography_spectrum: 0.3020207234658301
color:
  saturation: 0.1776958690024912
  brandStrength: 0.377551
  lightness: 0.1693992533255368
  brandColors:
    - '#000000'
    - '#8b0506'
    - '#80972e'
    - '#ffffff'
    - '#404000'
  rhythmicContrast: 0.7720348697621375
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1778271263465285
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6084632d-96a5-4f1b-b127-c2d273a48458.png
name: Strawberry Estate
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Property Manager
    url: 'https://propertymanager.strawberry-estate.com'
    type: external
  - name: Landlord View
    url: 'https://landlordview.strawberry-estate.com'
    type: external
  - name: Tenant View
    url: 'https://tenantview.strawberry-estate.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe377525-ffee-412a-8929-fbcb0bd20661.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Cloud Based Property Management
purpose: []
