name: Strawberry Estate
favicon: null
layout_spectrum: 0.17782712634652853
typography_spectrum: 0.3020207234658301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8b0506'
    - '#80972e'
    - '#ffffff'
    - '#404000'
  brandStrength: 0.41926320316269994
  lightness: 0.16939925332553685
  saturation: 0.17769586900249124
  rhythmicContrast: 0.7720348697621375
purpose: []
